##########################################################################
#
#
#    Ingress Nginx server config
#
#
##########################################################################
ingress-nginx:
  fullnameOverride: ingress-nginx
  namespaceOverride: ingress-nginx
  tcp:
    5432: "postgres/cloud-postgresql:5432"
##########################################################################
#
#
#   Postgres Configs
#
#
##########################################################################
postgresql:
  fullnameOverride: cloud-postgresql
  architecture: standalone
  auth:
    database: fantasy_football
    postgresPassword: "admin"
  primary:
    name: fantasy_football_primary
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    networkPolicy:
      enabled: false
    persistence:
      size: 1Gi
##########################################################################
#
#
#   Open Telemetry Collector Configs
#
#
##########################################################################
opentelemetry-collector:
  extraEnvs:
    - name: OTLP_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: otlp-secret
          optional: false
    - name: OTLP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: otlp-secret
          optional: false
  mode: deployment
  image:
    repository: otel/opentelemetry-collector-k8s
  command:
    name: otelcol-k8s
  fullnameOverride: opentelemetry-collector
  namespaceOverride: sre
  config:
    exporters:
      otlphttp:
        auth:
          authenticator: basicauth/otlp
        endpoint: https://otlp-gateway-prod-ap-south-1.grafana.net/otlp
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      memory_ballast: {}
      basicauth/otlp:
        client_auth:
          username: ${env:OTLP_USERNAME}
          password: ${env:OTLP_PASSWORD}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    processors:
      batch: { }
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter: null
    service:
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
      extensions:
        - health_check
        - memory_ballast
        - basicauth/otlp
      pipelines:
        metrics:
          exporters:
            - otlphttp
          processors:
            - batch
          receivers:
            - otlp
        traces:
          exporters:
            - otlphttp
          processors:
            - batch
          receivers:
            - otlp
  resources:
    limits:
      cpu: 500m
      memory: 512Mi