##########################################################################
#
#
#    Prometheus config
#
#
##########################################################################
prometheus:
  fullnameOverride: prometheus
  forceNamespace: sre
  # alert manager is a dependency to prometheus chart
  # override values for alert manager chart
  alertmanager:
    namespaceOverride: sre
  # kube-state-metrics is a dependency to prometheus chart
  # override values for kube-state-metrics chart
  kube-state-metrics:
    namespaceOverride: sre
  # prometheus-node-exporter is a dependency to prometheus chart
  # override values for prometheus-node-exporter chart
  prometheus-node-exporter:
    namespaceOverride: sre
  # prometheus-pushgateway is a dependency to prometheus chart
  # override values for prometheus-pushgateway chart
  prometheus-pushgateway:
    namespaceOverride: sre
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - prometheus.domain.com
    persistentVolume:
      size: 1Gi
##########################################################################
#
#
#    Grafana config
#
#
##########################################################################
grafana:
  fullnameOverride: grafana
  namespaceOverride: sre
  adminUser: admin
  adminPassword: admin
  persistence:
    size: 1Gi
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - grafana.domain.com
##########################################################################
#
#
#    Ingress Nginx server config
#
#
##########################################################################
ingress-nginx:
  fullnameOverride: ingress-nginx
  namespaceOverride: ingress-nginx
  tcp:
    5432: "postgres/cloud-postgresql:5432"
##########################################################################
#
#
#    Spring cloud data flow configs
#
#
##########################################################################
spring-cloud-dataflow:
  namespaceOverride: data-flow
  server:
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 1Gi
        cpu: 500m
    ingress:
      enabled: true
      hostname: dataflow.domain.com
      ingressClassName: nginx
    configuration:
      accountName: fantasy-football
  skipper:
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 1Gi
        cpu: 500m
  deployer:
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 1Gi
        cpu: 500m
  mariadb:
    enabled: false
  externalDatabase:
    host: cloud-postgresql.postgres.svc.cluster.local
    port: 5432
    driver: org.postgresql.Driver
    scheme: postgresql
    password: admin
    dataflow:
      database: fantasy_football
      username: postgres
    skipper:
      database: fantasy_football
      username: postgres
    hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    enabled: false
##########################################################################
#
#
#   Postgres Configs
#
#
##########################################################################
postgresql:
  fullnameOverride: cloud-postgresql
  architecture: standalone
  auth:
    database: fantasy_football
    postgresPassword: "admin"
  primary:
    ingress:
      hosts:
        - host: postgresql.domain.com
          paths:
            - path: /
              pathType: Prefix
    ingressClassName: "nginx"
    name: fantasy_football_primary
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    networkPolicy:
      enabled: false
    persistence:
      size: 1Gi
##########################################################################
#
#
#    Argo CD Configs
#
#
##########################################################################
argo-cd:
  crds:
    keep: false
  fullnameOverride: argo-cd
  global:
    domain: argocd.domain.com
    image:
      imagePullPolicy: Always
    logging:
      format: json
  configs:
    params:
      "server.insecure": true
    secret:
      argocdServerAdminPassword: $2a$04$WLAz4NxM7uxh4EbEDwyvUe7dkMTYCMpdfbdTuSKELv8suyHV4SuH6
  repoServer:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  server:
    ingress:
      enabled: true
      hostname: argocd-server.domain.com
      ingressClassName: nginx
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  dex:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  redis:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  applicationSet:
    ingress:
      enabled: true
      hostname: argocd-applicationset.domain.com
      ingressClassName: nginx
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  notifications:
    enabled: false