apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube.fullname" . }}
  labels:
    {{- include "kube.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: fluentbit
          image: fluent/fluent-bit:latest
          restartPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 100m
              memory: 250Mi
          env:
            - name: OTLP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: otlp-secret
                  optional: false
            - name: OTLP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: otlp-secret
                  optional: false
          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.conf
          volumeMounts:
            - name: log-path
              mountPath: /app/logs
            - name: fluent-config
              mountPath: /fluent-bit/etc/conf/fluent-bit.conf
              subPath: conf/fluent-bit.conf
            - name: multiline-parser-config
              mountPath: /fluent-bit/etc/conf/multiline-parser.conf
              subPath: multiline-parser/multiline-parser.conf
            - name: parser-config
              mountPath: /fluent-bit/etc/conf/parsers.conf
              subPath: parsers/parsers.conf
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: log-path
              mountPath: /app/logs/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: log-path
          emptyDir: { }
        - name: fluent-config
          configMap:
            name: fluent-bit-config
            items:
              - key: fluent-bit.conf
                path: conf/fluent-bit.conf
        - name: parser-config
          configMap:
            name: fluent-bit-config
            items:
              - key: parsers.conf
                path: parsers/parsers.conf
        - name: multiline-parser-config
          configMap:
            name: fluent-bit-config
            items:
              - key: multiline-parser.conf
                path: multiline-parser/multiline-parser.conf
  strategy:
    rollingUpdate:
      maxSurge: {{ add1 .Values.replicaCount }}
      maxUnavailable: 0