apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |-
    
    [SERVICE]
      Flush        1
      Log_Level    error
      parsers_file multiline-parser.conf
      parsers_file parsers.conf
    
    [INPUT]
      Name     tail
      Path     /app/logs/*.log
      multiline.parser multiline-regex-test
    
    [FILTER]
      Name parser
      Match *
      Key_Name log
      Parser json
    
    [OUTPUT]
      Name         loki
      Match        *
      Host         grafana-loki-gateway.sre.svc.cluster.local
      Port         80
      TLS          Off
      TLS.Verify   Off
      Labels       job=fluentbit
    
    [OUTPUT]
      Name stdout
      Match *
  parsers.conf: |-
    [PARSER]
      Name   json
      Format json
      Time_Key @timestamp
      Time_Format %Y-%m-%dT%H:%M:%S.%L %Z
      Time_Keep Off
  multiline-parser.conf: |-
    [MULTILINE_PARSER]
      name          multiline-regex-test
      type          regex
      flush_timeout 1000
      #
      # Regex rules for multiline parsing
      # ---------------------------------
      #
      # configuration hints:
      #
      #  - first state always has the name: start_state
      #  - every field in the rule must be inside double quotes
      #
      # rules |   state name  | regex pattern                  | next state
      # ------|---------------|--------------------------------------------
      rule      "start_state"   "/([a-zA-Z]+ \d+ \d+\:\d+\:\d+)(.*)/"  "cont"
      rule      "cont"          "/^\s+at.*/"                     "cont"